// This file is generated by Gemini.

'use server';

/**
 * @fileOverview An AI agent that suggests relevant tags and categories for task descriptions.
 *
 * - suggestTaskTags - A function that handles the task tag suggestion process.
 * - SuggestTaskTagsInput - The input type for the suggestTaskTags function.
 * - SuggestTaskTagsOutput - The return type for the suggestTaskTags function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestTaskTagsInputSchema = z.object({
  taskDescription: z
    .string()
    .describe('The description of the task for which tags are to be suggested.'),
});

export type SuggestTaskTagsInput = z.infer<typeof SuggestTaskTagsInputSchema>;

const SuggestTaskTagsOutputSchema = z.object({
  suggestedTags: z
    .array(z.string())
    .describe('An array of suggested tags for the task.'),
  suggestedCategories: z
    .array(z.string())
    .describe('An array of suggested categories for the task.'),
});

export type SuggestTaskTagsOutput = z.infer<typeof SuggestTaskTagsOutputSchema>;

export async function suggestTaskTags(input: SuggestTaskTagsInput): Promise<SuggestTaskTagsOutput> {
  return suggestTaskTagsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestTaskTagsPrompt',
  input: {schema: SuggestTaskTagsInputSchema},
  output: {schema: SuggestTaskTagsOutputSchema},
  prompt: `You are an AI assistant that analyzes task descriptions and suggests relevant tags and categories to help users better organize their tasks.

  Analyze the following task description and suggest relevant tags and categories. Return the suggested tags and categories as arrays of strings.

  Task Description: {{{taskDescription}}}
  `,
});

const suggestTaskTagsFlow = ai.defineFlow(
  {
    name: 'suggestTaskTagsFlow',
    inputSchema: SuggestTaskTagsInputSchema,
    outputSchema: SuggestTaskTagsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
